import type { Metadata } from "next";
import { Poppins, Roboto } from "next/font/google";
import '../styles/global.css';

const geistSans = Poppins({
  subsets: ['latin'],
  weight: ["300", "400", "500", "600", "700"]
});

const roboto = Roboto({
  subsets: ['latin'],
  weight: ["100", "300", "400", "500", "700", "900"]
})


export const metadata: Metadata = {
  title: "Sa",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={`${roboto.className} ${geistSans.className}`}>
        {children}
      </body>
    </html>
  );
}
